name: External Link Check (Nightly)
on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC daily
  workflow_dispatch:

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install linkchecker
      - name: Build site
        run: mkdocs build --clean
      - name: Check links
        run: |
          linkchecker --ignore-url '^mailto:' --check-extern ./site
